#!/usr/bin/env python3
"""Regression tests for ``sealmark key-id``.

The key-id contract under test (see README):

* success: exit code 0, empty stderr, stdout is exactly one line
  ``spki-sha256:<64 lowercase hex digits>`` terminated by a single newline;
* the fingerprint is the SHA-256 of the SubjectPublicKeyInfo DER carried by
  the PEM block -- the public-key algorithm identifier and public key value
  are included; file name, path and the PEM text layout are not;
* at least RSA and Ed25519 SubjectPublicKeyInfo public keys are supported
  (EC P-256 is covered as well);
* the same key produces the same fingerprint under LF or CRLF line endings,
  any legal base64 line wrapping, no trailing newline, or trailing ASCII
  whitespace glued directly to the END marker with no line feed at all, and
  after the file is moved or renamed -- even when large amounts of
  surrounding ASCII whitespace carry the block through several 64 KiB read
  passes, with the begin marker, base64 data, end marker, the first bytes of
  the glued trailing whitespace and the two bytes of each CRLF straddling
  read boundaries;
* the fingerprint is independently recomputed here with hashlib over the DER
  obtained from the cryptography package, and one Ed25519 case is pinned to a
  known answer;
* the file must contain exactly one PEM block wrapped in the literal
  ``PUBLIC KEY`` label, with only ASCII whitespace before or after it. Empty
  files, damaged/truncated encodings, non-canonical base64, more than one key,
  stray non-whitespace bytes (even several read passes beyond the block),
  truncation leaving a marker or the base64 body unfinished at a read
  boundary, private keys, certificates and other public-key wrappers (e.g.
  PKCS#1 ``RSA PUBLIC KEY``) all fail;
* an intact PEM envelope (correct markers, legal base64, complete outer
  structure) is not enough: the decoded payload must be canonical
  SubjectPublicKeyInfo DER, not merely BER the crypto library can parse.
  Non-minimal length-of-length encodings, RSA INTEGERs with surplus leading
  zero bytes, and fields whose declared length does not match their content
  are rejected even when the bytes still describe the original key -- the
  command never normalizes such input to a canonical re-encoding and never
  prints a fingerprint for it. The one apparent oddity that IS canonical --
  an RSA modulus' mandatory leading zero when its top bit is set -- stays
  accepted;
* missing path / directory / unreadable input / invalid key content: exit
  code 1 with empty stdout and a stderr message containing the path -- the
  command never falls back to a file digest and never prints a partial
  fingerprint;
* missing/empty/extra arguments: exit code 2, empty stdout, usage text on
  stderr mentioning ``key-id``.

The read-failure cases reuse the LD_PRELOAD fault injector shared with the
other suites ($SEALMARK_READFAIL_PRELOAD): a regular file opens fine and
read() then fails with EIO after an exact number of delivered bytes. Those
tests skip when the injector is unavailable. Key material and all files are
generated by the tests themselves inside a fresh temporary directory.
"""

import base64
import datetime
import hashlib
import os
import re
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec, ed25519, rsa
from cryptography.x509.oid import NameOID

# Must match the read buffer size in src/main.cpp.
CHUNK_SIZE = 64 * 1024

SEALMARK_BIN = os.environ.get("SEALMARK_BIN")
READFAIL_PRELOAD = os.environ.get("SEALMARK_READFAIL_PRELOAD")

requires_readfail_preload = unittest.skipUnless(
    READFAIL_PRELOAD and Path(READFAIL_PRELOAD).is_file(),
    "SEALMARK_READFAIL_PRELOAD is unavailable; mid-read failure cannot be "
    "injected on this platform",
)

OUTPUT_RE = re.compile(rb"\Aspki-sha256:[0-9a-f]{64}\n\Z")

# SubjectPublicKeyInfo DER of the Ed25519 public key derived from the
# all-zero 32-byte private scalar, pinned so the wire value itself is
# regression-tested (not just self-consistency between runs).
ED25519_ZERO_SPKI_DER = bytes.fromhex(
    "302a300506032b65700321003b6a27bcceb6a42d62a3a8d02a6f0d7365321577"
    "1de243a63ac048a18b59da29"
)
ED25519_ZERO_FINGERPRINT = (
    "spki-sha256:339e2ff917630507b6a423b5ce084e285d1fa65d93b3e27a6195d3bbebc9ae23"
)

BEGIN = b"-----BEGIN PUBLIC KEY-----"
END = b"-----END PUBLIC KEY-----"


def spki_der(pub):
    return pub.public_bytes(
        serialization.Encoding.DER,
        serialization.PublicFormat.SubjectPublicKeyInfo,
    )


def fingerprint_of_der(der):
    return "spki-sha256:" + hashlib.sha256(der).hexdigest()


def wrap_public_pem(der, width=64, newline=b"\n", final_newline=True,
                    begin=BEGIN, end=END):
    """Build a PUBLIC KEY PEM with explicit control over its text layout."""
    encoded = base64.b64encode(der)
    lines = [encoded[i:i + width] for i in range(0, len(encoded), width)]
    out = begin + newline + newline.join(lines) + newline + end
    if final_newline:
        out += newline
    return out


# --- Minimal DER builders for the internal-encoding tests ------------------
#
# key-id must fingerprint exactly the canonical SubjectPublicKeyInfo DER and
# reject payloads whose PEM envelope is intact but whose inner encoding is
# not canonical DER -- even when those bytes still describe the same key.
# These builders compose an SPKI from its parts so a test can disturb one
# length field or INTEGER content at a time while keeping every other level
# canonical; the undisturbed output is pinned against the cryptography
# package's own encoding in the tests below.

RSA_ALGORITHM_OID = bytes.fromhex("2a864886f70d010101")  # rsaEncryption
ED25519_ALGORITHM_OID = bytes.fromhex("2b6570")  # Ed25519


def der_length(length, force_long_form=False, extra_length_bytes=0):
    """Encode a DER length, optionally in a non-minimal (non-DER) form."""
    if not force_long_form and not extra_length_bytes and length < 0x80:
        return bytes([length])
    raw = length.to_bytes(max(1, (length.bit_length() + 7) // 8), "big")
    raw = b"\x00" * extra_length_bytes + raw
    return bytes([0x80 | len(raw)]) + raw


def der_tlv(tag, content, declared_length=None, **length_kwargs):
    length = len(content) if declared_length is None else declared_length
    return bytes([tag]) + der_length(length, **length_kwargs) + content


def der_content(encoded):
    """Return the content bytes of a single DER TLV (canonical lengths)."""
    first = encoded[1]
    if first < 0x80:
        header, length = 2, first
    else:
        count = first & 0x7F
        header = 2 + count
        length = int.from_bytes(encoded[2:header], "big")
    assert length == len(encoded) - header, "not one complete DER TLV"
    return encoded[header:]


def der_integer_content(value):
    """Canonical DER INTEGER content for a non-negative value: two's
    complement, so a leading 0x00 is present exactly when the value's top
    bit is set (without it the integer would decode as negative)."""
    raw = value.to_bytes(max(1, (value.bit_length() + 7) // 8), "big")
    return (b"\x00" if raw[0] >= 0x80 else b"") + raw


def build_rsa_spki_der(modulus_content, exponent_content, *,
                       outer=None, algid=None, bit_string=None,
                       inner=None, modulus=None, exponent=None,
                       declared_delta=None):
    """Build an RSA SPKI DER from the two INTEGER contents. Each level
    keyword overrides the der_tlv kwargs of that nesting level; a
    (level, delta) ``declared_delta`` makes that level's declared length
    differ from its actual content length."""
    level, delta = declared_delta or (None, 0)

    def tlv(tag, content, level_name, kwargs):
        kwargs = dict(kwargs or {})
        if level_name == level:
            kwargs["declared_length"] = len(content) + delta
        return der_tlv(tag, content, **kwargs)

    modulus_tlv = tlv(0x02, modulus_content, "modulus", modulus)
    exponent_tlv = tlv(0x02, exponent_content, "exponent", exponent)
    inner_tlv = tlv(0x30, modulus_tlv + exponent_tlv, "inner", inner)
    algid_tlv = tlv(
        0x30, der_tlv(0x06, RSA_ALGORITHM_OID) + der_tlv(0x05, b""),
        "algid", algid,
    )
    bit_string_tlv = tlv(0x03, b"\x00" + inner_tlv, "bit_string", bit_string)
    return tlv(0x30, algid_tlv + bit_string_tlv, "outer", outer)


def build_ed25519_spki_der(raw_key, *, outer=None, algid=None,
                           bit_string=None, declared_delta=None):
    """Build an Ed25519 SPKI DER from the raw 32-byte public key; the
    keywords work as in build_rsa_spki_der."""
    level, delta = declared_delta or (None, 0)

    def tlv(tag, content, level_name, kwargs):
        kwargs = dict(kwargs or {})
        if level_name == level:
            kwargs["declared_length"] = len(content) + delta
        return der_tlv(tag, content, **kwargs)

    algid_tlv = tlv(0x30, der_tlv(0x06, ED25519_ALGORITHM_OID), "algid", algid)
    bit_string_tlv = tlv(0x03, b"\x00" + raw_key, "bit_string", bit_string)
    return tlv(0x30, algid_tlv + bit_string_tlv, "outer", outer)


# Every ASCII whitespace byte accepted around the PEM block (must match
# isAsciiSpace in src/main.cpp): space, tab, LF, vertical tab, form feed, CR.
AROUND_BLOCK_WHITESPACE = b" \t\n\x0b\x0c\r"


def ascii_whitespace(length):
    """Build a `length`-byte run using all six legal surrounding whitespace
    bytes, cycling deterministically (no randomness so a failing offset is
    reproducible)."""
    pattern = AROUND_BLOCK_WHITESPACE
    return pattern * (length // len(pattern)) + pattern[:length % len(pattern)]


class SealmarkKeyIdTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        if not SEALMARK_BIN:
            raise RuntimeError(
                "SEALMARK_BIN is not set; point it at the sealmark executable"
            )
        if not Path(SEALMARK_BIN).is_file():
            raise RuntimeError(f"SEALMARK_BIN does not point to a file: {SEALMARK_BIN}")

        cls.rsa_priv = rsa.generate_private_key(public_exponent=65537,
                                                key_size=2048)
        cls.rsa_pub = cls.rsa_priv.public_key()
        cls.rsa_der = spki_der(cls.rsa_pub)
        cls.rsa_pem = cls.rsa_pub.public_bytes(
            serialization.Encoding.PEM,
            serialization.PublicFormat.SubjectPublicKeyInfo,
        )

        cls.ed_priv = ed25519.Ed25519PrivateKey.generate()
        cls.ed_pub = cls.ed_priv.public_key()
        cls.ed_der = spki_der(cls.ed_pub)
        cls.ed_pem = cls.ed_pub.public_bytes(
            serialization.Encoding.PEM,
            serialization.PublicFormat.SubjectPublicKeyInfo,
        )

        cls.other_ed_priv = ed25519.Ed25519PrivateKey.generate()
        cls.other_ed_der = spki_der(cls.other_ed_priv.public_key())

        cls.ec_priv = ec.generate_private_key(ec.SECP256R1())
        cls.ec_der = spki_der(cls.ec_priv.public_key())

        # An RSA key whose modulus has its most significant bit set, so the
        # canonical DER INTEGER content carries the mandatory leading 0x00
        # (without it the integer would decode as negative). Each generated
        # key has a good chance of qualifying; regenerate until one does.
        hi_priv = rsa.generate_private_key(public_exponent=65537,
                                           key_size=2048)
        while hi_priv.public_key().public_numbers().n.bit_length() < 2048:
            hi_priv = rsa.generate_private_key(public_exponent=65537,
                                               key_size=2048)
        cls.rsa_hi_pub = hi_priv.public_key()
        cls.rsa_hi_der = spki_der(cls.rsa_hi_pub)
        cls.rsa_hi_modulus_content = der_integer_content(
            cls.rsa_hi_pub.public_numbers().n
        )
        cls.rsa_hi_exponent_content = der_integer_content(
            cls.rsa_hi_pub.public_numbers().e
        )

        cls.ed_raw = cls.ed_pub.public_bytes(
            serialization.Encoding.Raw, serialization.PublicFormat.Raw
        )

    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="sealmark-keyid-test-"))
        self.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)

    def run_sealmark(self, *args):
        return subprocess.run([SEALMARK_BIN, *args], capture_output=True)

    def run_key_id(self, path_arg):
        return self.run_sealmark("key-id", path_arg)

    def write_file(self, relative_path, content):
        path = self.tmp / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
        return path

    def assertFingerprintOk(self, result, der):
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stderr, b"")
        self.assertRegex(result.stdout, OUTPUT_RE)
        self.assertEqual(len(result.stdout), len("spki-sha256:") + 64 + 1)
        self.assertEqual(
            result.stdout,
            (fingerprint_of_der(der) + "\n").encode("ascii"),
        )

    def assertRejected(self, result, path):
        self.assertEqual(result.returncode, 1, result.stderr)
        self.assertEqual(result.stdout, b"")
        self.assertIn(os.fsencode(str(path)), result.stderr)
        self.assertNotIn(b"spki-sha256", result.stderr)
        self.assertNotIn(b"Usage", result.stderr)
        self.assertTrue(result.stderr.endswith(b"\n"))

    # -- success ---------------------------------------------------------

    def test_rsa_fingerprint_is_sha256_of_spki_der(self):
        path = self.write_file("rsa.pub", self.rsa_pem)
        self.assertFingerprintOk(self.run_key_id(str(path)), self.rsa_der)

    def test_ed25519_fingerprint_is_sha256_of_spki_der(self):
        path = self.write_file("ed25519.pub", self.ed_pem)
        self.assertFingerprintOk(self.run_key_id(str(path)), self.ed_der)

    def test_ec_p256_fingerprint_is_sha256_of_spki_der(self):
        pem = self.ec_priv.public_key().public_bytes(
            serialization.Encoding.PEM,
            serialization.PublicFormat.SubjectPublicKeyInfo,
        )
        path = self.write_file("ec.pub", pem)
        self.assertFingerprintOk(self.run_key_id(str(path)), self.ec_der)

    def test_ed25519_known_answer(self):
        zero_priv = ed25519.Ed25519PrivateKey.from_private_bytes(b"\x00" * 32)
        zero_pub = zero_priv.public_key()
        self.assertEqual(spki_der(zero_pub), ED25519_ZERO_SPKI_DER)
        path = self.write_file(
            "zero-ed.pub",
            zero_pub.public_bytes(
                serialization.Encoding.PEM,
                serialization.PublicFormat.SubjectPublicKeyInfo,
            ),
        )

        result = self.run_key_id(str(path))

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stderr, b"")
        self.assertEqual(
            result.stdout, (ED25519_ZERO_FINGERPRINT + "\n").encode("ascii")
        )

    def test_lf_crlf_and_any_base64_wrapping_give_same_fingerprint(self):
        expected = fingerprint_of_der(self.rsa_der)
        variants = {
            "lf64.pub": wrap_public_pem(self.rsa_der, 64, b"\n"),
            "crlf64.pub": wrap_public_pem(self.rsa_der, 64, b"\r\n"),
            "lf1.pub": wrap_public_pem(self.rsa_der, 1, b"\n"),
            "crlf4.pub": wrap_public_pem(self.rsa_der, 4, b"\r\n"),
            "lf73.pub": wrap_public_pem(self.rsa_der, 73, b"\n"),
            "single_line.pub": wrap_public_pem(
                self.rsa_der, len(base64.b64encode(self.rsa_der)), b"\n"
            ),
            "no_final_newline.pub":
                wrap_public_pem(self.rsa_der, 64, b"\n", final_newline=False),
            "crlf_no_final_newline.pub":
                wrap_public_pem(self.rsa_der, 64, b"\r\n", final_newline=False),
        }
        seen = set()
        for name, content in variants.items():
            with self.subTest(name=name):
                path = self.write_file(Path("wrap", name), content)
                result = self.run_key_id(str(path))
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertEqual(result.stderr, b"")
                self.assertEqual(
                    result.stdout, (expected + "\n").encode("ascii")
                )
                seen.add(result.stdout)
        # All layouts of the same key collapse to one fingerprint.
        self.assertEqual(seen, {(expected + "\n").encode("ascii")})

    def test_ascii_whitespace_around_block_is_ignored(self):
        expected = fingerprint_of_der(self.ed_der)
        ws = b" \t\r\n\x0b\x0c"
        variants = [
            ws + self.ed_pem,
            self.ed_pem + ws,
            ws + self.ed_pem + ws,
            b"\n" + self.ed_pem,
            self.ed_pem.replace(b"\n", b"\r\n") + b"\n",
        ]
        for i, content in enumerate(variants):
            with self.subTest(variant=i):
                path = self.write_file(f"ws/{i}.pub", content)
                result = self.run_key_id(str(path))
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertEqual(result.stderr, b"")
                self.assertEqual(
                    result.stdout, (expected + "\n").encode("ascii")
                )

    def test_whitespace_glued_directly_to_end_marker_is_ignored(self):
        # A complete END marker needs no line feed at all: any ASCII
        # whitespace byte may follow its final '-' immediately -- a lone
        # space, a CR then a tab, vertical tab/form feed -- and EOF may
        # follow right away or after arbitrarily many such bytes. The
        # fingerprint is the same as with the conventional trailing LF.
        expected = fingerprint_of_der(self.ed_der)
        block = wrap_public_pem(self.ed_der, 64, b"\n", final_newline=False)
        self.assertFalse(block.endswith((b"\n", b"\r")))
        block_crlf = wrap_public_pem(
            self.ed_der, 64, b"\r\n", final_newline=False
        )
        tails = [
            b" ", b"\t", b"\r", b"\n", b"\x0b", b"\x0c",
            b"\r\t", b"\x0b\x0c ", AROUND_BLOCK_WHITESPACE,
            b" " + AROUND_BLOCK_WHITESPACE * 100,
            b"\r\n " + AROUND_BLOCK_WHITESPACE,
        ]
        variants = [block + tail for tail in tails]
        variants += [block_crlf + b" ", block_crlf + b"\r\t   "]
        for i, content in enumerate(variants):
            with self.subTest(variant=i):
                path = self.write_file(f"glued/{i}.pub", content)
                result = self.run_key_id(str(path))
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertEqual(result.stderr, b"")
                self.assertEqual(
                    result.stdout, (expected + "\n").encode("ascii")
                )

    def test_move_and_rename_do_not_change_fingerprint(self):
        names = [
            "key.pub",
            "nested/dir/public key.pub",
            "目录/公钥 副本.pub",
            "deep/deeper/key 0.tmp",
        ]
        outputs = set()
        for name in names:
            with self.subTest(name=name):
                path = self.write_file(Path(name), self.ed_pem)
                result = self.run_key_id(str(path))
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertEqual(result.stderr, b"")
                outputs.add(result.stdout)
        self.assertEqual(len(outputs), 1)
        self.assertEqual(
            outputs.pop(),
            (fingerprint_of_der(self.ed_der) + "\n").encode("ascii"),
        )

    def test_different_keys_have_different_fingerprints(self):
        self.assertNotEqual(self.ed_der, self.other_ed_der)
        p1 = self.write_file("a.pub", self.ed_pem)
        p2 = self.write_file(
            "b.pub",
            self.other_ed_priv.public_key().public_bytes(
                serialization.Encoding.PEM,
                serialization.PublicFormat.SubjectPublicKeyInfo,
            ),
        )
        r1 = self.run_key_id(str(p1))
        r2 = self.run_key_id(str(p2))
        self.assertEqual(r1.returncode, 0, r1.stderr)
        self.assertEqual(r2.returncode, 0, r2.stderr)
        self.assertNotEqual(r1.stdout, r2.stdout)
        self.assertEqual(
            r1.stdout,
            (fingerprint_of_der(self.ed_der) + "\n").encode("ascii"),
        )
        self.assertEqual(
            r2.stdout,
            (fingerprint_of_der(self.other_ed_der) + "\n").encode("ascii"),
        )

    def test_input_file_is_not_modified(self):
        path = self.write_file("rsa.pub", self.rsa_pem)
        before = path.stat()
        content_before = path.read_bytes()
        result = self.run_key_id(str(path))
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(path.read_bytes(), content_before)
        self.assertEqual(path.stat().st_size, before.st_size)

    # -- multiple read passes / chunk-boundary regression ----------------
    #
    # The file is delivered to the parser in fixed CHUNK_SIZE-byte passes, so
    # every parser state must survive a boundary between passes. A PEM block
    # is short, so surrounding ASCII whitespace is used to push individual
    # block bytes across those boundaries; the padding itself never enters the
    # fingerprint. These tests pin that behavior for both RSA and Ed25519.

    def _assert_fingerprint_for_content(self, content, der, name):
        self.assertGreater(
            len(content), CHUNK_SIZE,
            "test setup must force more than one read pass",
        )
        path = self.write_file(name, content)
        self.assertFingerprintOk(self.run_key_id(str(path)), der)

    def test_large_whitespace_padding_forces_multiple_read_passes(self):
        for key_name, der, pem in (
            ("rsa", self.rsa_der, self.rsa_pem),
            ("ed25519", self.ed_der, self.ed_pem),
        ):
            variants = {
                "pad-both.pub":
                    ascii_whitespace(CHUNK_SIZE + 17) + pem
                    + ascii_whitespace(2 * CHUNK_SIZE + 101),
                "pad-before.pub":
                    ascii_whitespace(2 * CHUNK_SIZE - 1) + pem,
                "pad-after.pub":
                    pem + ascii_whitespace(3 * CHUNK_SIZE + 5),
                "pad-crlf.pub":
                    ascii_whitespace(CHUNK_SIZE - 1)
                    + pem.replace(b"\n", b"\r\n")
                    + ascii_whitespace(CHUNK_SIZE + 1),
            }
            for suffix, content in variants.items():
                with self.subTest(key=key_name, variant=suffix):
                    self._assert_fingerprint_for_content(
                        content, der, f"multi/{key_name}/{suffix}"
                    )

    def test_each_whitespace_kind_alone_pads_across_reads(self):
        # All six legal surrounding whitespace bytes, each on its own and in
        # a run long enough to span several passes, before and after the
        # block.
        for byte in b" \t\r\n\x0b\x0c":
            padding = bytes([byte]) * (CHUNK_SIZE + 13)
            content = padding + self.ed_pem + padding
            with self.subTest(byte=byte):
                self._assert_fingerprint_for_content(
                    content, self.ed_der, f"multi/ws-{byte:#04x}.pub"
                )

    def test_boundary_swept_across_begin_marker(self):
        # For every k the boundary between the first two reads falls right
        # after the k-th byte of the BEGIN marker (k == 0: immediately before
        # it; k == len(BEGIN): between the complete marker and its newline).
        for k in range(len(BEGIN) + 1):
            with self.subTest(k=k):
                content = (
                    ascii_whitespace(CHUNK_SIZE - k) + self.rsa_pem
                    + ascii_whitespace(CHUNK_SIZE)
                )
                self._assert_fingerprint_for_content(
                    content, self.rsa_der, f"multi/begin-sweep/{k}.pub"
                )

    def test_boundary_swept_across_whole_block_lf_and_crlf(self):
        # Exhaustive sweep: every byte position of both the LF and CRLF block
        # layouts becomes the first byte of a later read pass, with trailing
        # whitespace crossing yet another boundary. In particular this lands
        # the CR and the LF of every CRLF pair in different passes.
        for ending_name, newline in (("lf", b"\n"), ("crlf", b"\r\n")):
            block = wrap_public_pem(self.rsa_der, 64, newline)
            for offset in range(len(block) + 1):
                with self.subTest(ending=ending_name, offset=offset):
                    content = (
                        ascii_whitespace(CHUNK_SIZE - offset) + block
                        + ascii_whitespace(CHUNK_SIZE + 1)
                    )
                    self._assert_fingerprint_for_content(
                        content, self.rsa_der,
                        f"multi/sweep/{ending_name}/{offset}.pub",
                    )

    def test_each_crlf_pair_is_split_between_read_passes(self):
        # Targeted version of the CRLF guarantee: for every CR in the block,
        # that CR is the final byte of one pass and its LF the first byte of
        # the next (header line, each base64 line, and the END line).
        block = wrap_public_pem(self.ed_der, 16, b"\r\n")
        cr_positions = [i for i, c in enumerate(block) if c == ord("\r")]
        self.assertTrue(cr_positions)
        for cr_pos in cr_positions:
            with self.subTest(cr_pos=cr_pos):
                content = (
                    ascii_whitespace(CHUNK_SIZE - cr_pos - 1) + block
                    + ascii_whitespace(CHUNK_SIZE)
                )
                self._assert_fingerprint_for_content(
                    content, self.ed_der,
                    f"multi/crlf-split/{cr_pos}.pub",
                )

    def test_alternative_base64_wrapping_spans_read_passes(self):
        encoded_len = len(base64.b64encode(self.rsa_der))
        layouts = (
            (1, b"\n"), (4, b"\r\n"), (16, b"\n"), (64, b"\r\n"),
            (73, b"\n"), (encoded_len, b"\n"),
        )
        # Offsets chosen to put a quantum start, a quantum middle and a line
        # boundary on either side of a read boundary.
        offsets = (0, 1, 2, 3, 4, 5, 7, 15, 16, 31, 63, 64, 65, 100)
        for width, newline in layouts:
            block = wrap_public_pem(self.rsa_der, width, newline)
            for offset in offsets:
                if offset > len(block):
                    continue
                with self.subTest(width=width, newline=newline, offset=offset):
                    content = (
                        ascii_whitespace(CHUNK_SIZE - offset) + block
                        + ascii_whitespace(CHUNK_SIZE)
                    )
                    self._assert_fingerprint_for_content(
                        content, self.rsa_der,
                        f"multi/wrap/{width}-{offset}.pub",
                    )

    def test_complete_end_marker_at_eof_without_newline_is_valid(self):
        # Normal completion versus truncation: a fully matched END marker is
        # valid exactly at EOF with no trailing newline, including when its
        # last bytes are delivered by a second read pass. A legal trailing
        # newline or surrounding whitespace must give the same fingerprint.
        block = wrap_public_pem(self.rsa_der, 64, b"\n", final_newline=False)
        block_with_newline = wrap_public_pem(
            self.rsa_der, 64, b"\n", final_newline=True
        )
        length = len(block)
        variants = {
            # Final '-' of END is the first byte of the second pass and EOF
            # immediately follows -- a complete marker ending the file.
            "end-final-byte-in-second-pass.pub":
                ascii_whitespace(CHUNK_SIZE - length + 1) + block,
            # Same block, but the legal trailing newline is what the second
            # pass delivers; fingerprint must be identical.
            "newline-in-second-pass.pub":
                ascii_whitespace(CHUNK_SIZE - length) + block_with_newline,
            # END marker itself straddles the boundary (3 bytes in the first
            # pass, 21 in the second), EOF right after its last byte.
            "end-split-then-eof.pub":
                ascii_whitespace(CHUNK_SIZE - length + 21) + block,
            # END straddles the boundary, then its newline and a postamble
            # long enough to reach a third pass.
            "end-split-then-whitespace.pub":
                ascii_whitespace(CHUNK_SIZE - length + 21)
                + block_with_newline + ascii_whitespace(CHUNK_SIZE + 7),
        }
        for name, content in variants.items():
            with self.subTest(variant=name):
                self._assert_fingerprint_for_content(
                    content, self.rsa_der, f"multi/eof/{name}"
                )

    def test_glued_trailing_whitespace_survives_read_boundaries(self):
        # The END marker and the whitespace glued directly to it may be split
        # between read passes in every alignment: the boundary sweeps from
        # several bytes before the marker completes (marker straddles) through
        # several trailing bytes after it. The first byte past the complete
        # marker is deliberately a space, so the old "must start with a line
        # feed" rule rejected the splits that delivered that space in a later
        # pass. Trailing whitespace spanning further passes adds no state
        # beyond the fixed-size parser.
        block = wrap_public_pem(self.rsa_der, 64, b"\n", final_newline=False)
        tail = b" \t\r" + ascii_whitespace(CHUNK_SIZE + 7)
        for delta in range(-(len(END) + 1), 9):
            with self.subTest(delta=delta):
                # delta < 0: the first pass ends -delta bytes before the END
                # marker completes; delta >= 0: delta trailing bytes land in
                # the first pass.
                content = (
                    ascii_whitespace(CHUNK_SIZE - len(block) - delta)
                    + block + tail
                )
                self._assert_fingerprint_for_content(
                    content, self.rsa_der, f"multi/glued/{delta}.pub"
                )

    def test_non_whitespace_after_glued_whitespace_run_is_rejected(self):
        # Once the complete END marker is followed by whitespace, the parser
        # must keep classifying bytes to EOF: a stray byte or a second key is
        # rejected whether it follows the marker directly or a long whitespace
        # run, including when the marker/whitespace join straddles a boundary.
        block = wrap_public_pem(self.ed_der, 64, b"\n", final_newline=False)
        for stray in (b"x", b" extra\n", self.rsa_pem, BEGIN + b"\n"):
            for gap in (0, 1, 3, CHUNK_SIZE - 1, CHUNK_SIZE,
                        2 * CHUNK_SIZE + 71):
                with self.subTest(stray=stray[:8], gap=gap):
                    content = block + b" " + ascii_whitespace(gap) + stray
                    path = self.write_file(
                        f"multi/glued-stray/{gap}.pub", content
                    )
                    self.assertRejected(self.run_key_id(str(path)), path)

    def test_second_key_far_beyond_first_block_is_rejected(self):
        # The parser must keep checking all the way to EOF: the second key
        # only appears several read passes after the first block completed, so
        # accepting after the first END would print a fingerprint first.
        far = 3 * CHUNK_SIZE + 123
        variants = (
            self.rsa_pem + ascii_whitespace(far) + self.ed_pem,
            self.rsa_pem + ascii_whitespace(far) + self.ed_pem
            + ascii_whitespace(CHUNK_SIZE),
            self.rsa_pem + ascii_whitespace(2 * CHUNK_SIZE)
            + BEGIN + b"\n",
            ascii_whitespace(CHUNK_SIZE) + b"X"
            + ascii_whitespace(CHUNK_SIZE) + self.rsa_pem,
        )
        for i, content in enumerate(variants):
            with self.subTest(variant=i):
                path = self.write_file(f"multi/far/{i}.pub", content)
                self.assertRejected(self.run_key_id(str(path)), path)

    def test_stray_byte_far_after_block_is_rejected(self):
        for stray in (b"X", b".", b"\x00", b"\xff"):
            variants = (
                self.ed_pem + ascii_whitespace(2 * CHUNK_SIZE + 71) + stray,
                self.ed_pem + ascii_whitespace(2 * CHUNK_SIZE) + stray
                + ascii_whitespace(CHUNK_SIZE),
            )
            for i, content in enumerate(variants):
                with self.subTest(stray=stray, variant=i):
                    path = self.write_file(
                        f"multi/stray/{stray[0]:#04x}-{i}.pub", content
                    )
                    self.assertRejected(self.run_key_id(str(path)), path)

    def test_truncated_begin_marker_near_read_boundary_is_rejected(self):
        # "Near a boundary" in two distinct ways: the cut lands exactly as a
        # read pass ends (second_bytes == 0), or marker bytes are split across
        # passes and the file ends mid-marker inside the following pass. A
        # complete marker with its newline cut (including CRLF cut after CR)
        # is unfinished in the same sense.
        cases = []
        for cut in (1, 5, 10, 18, len(BEGIN) - 1, len(BEGIN)):
            for in_first_pass in (0, 1, cut // 2, cut):
                cases.append(
                    ascii_whitespace(CHUNK_SIZE - in_first_pass) + BEGIN[:cut]
                )
        # Whole marker in the first pass, CR at the first byte of the second
        # pass with its LF cut: a CRLF header split, then truncated.
        cases.append(
            ascii_whitespace(CHUNK_SIZE - len(BEGIN) - 1) + BEGIN + b"\r"
        )
        for i, content in enumerate(cases):
            with self.subTest(case=i, length=len(content)):
                path = self.write_file(f"multi/trunc-begin/{i}.pub", content)
                self.assertRejected(self.run_key_id(str(path)), path)

    def test_truncated_end_marker_near_read_boundary_is_rejected(self):
        prefix = self.rsa_pem[:self.rsa_pem.index(END)]
        cases = []
        for cut in (1, 5, 10, len(END) - 1):
            for in_first_pass in (0, 1, 3, cut):
                if in_first_pass > cut:
                    continue
                # in_first_pass END bytes arrive in the pass that already
                # carries the whole body prefix; the other cut - in_first_pass
                # bytes arrive in the next pass, then the file ends.
                cases.append(
                    ascii_whitespace(
                        CHUNK_SIZE - len(prefix) - in_first_pass
                    )
                    + prefix + END[:cut]
                )
        for i, content in enumerate(cases):
            with self.subTest(case=i, length=len(content)):
                path = self.write_file(f"multi/trunc-end/{i}.pub", content)
                self.assertRejected(self.run_key_id(str(path)), path)

    def test_truncated_base64_body_near_read_boundary_is_rejected(self):
        encoded = base64.b64encode(self.rsa_der)
        heads = []
        # Dangling final quantum (1-3 base64 chars), no END line: EOF while
        # body data is expected, split right at the boundary.
        for tail in (1, 2, 3):
            head = BEGIN + b"\n" + encoded[:64 + tail]
            heads.append(head)
        # Body ends on a quantum boundary but the END line never arrives.
        heads.append(BEGIN + b"\n" + encoded)
        # A body line ending in CR whose LF is cut by EOF.
        heads.append(BEGIN + b"\n" + encoded[:64] + b"\r")
        # Quantum-complete lines up to an unfinished last quantum followed by
        # an END line: the marker is found, but the base64 stream did not end
        # on a quantum boundary.
        heads.append(BEGIN + b"\n" + encoded[:-1] + b"\n" + END + b"\n")
        for i, head in enumerate(heads):
            with self.subTest(case=i):
                content = ascii_whitespace(CHUNK_SIZE - (len(head) - 1)) + head
                path = self.write_file(f"multi/trunc-body/{i}.pub", content)
                self.assertRejected(self.run_key_id(str(path)), path)

    # -- invalid content (exit code 1) -----------------------------------

    def test_empty_file_is_rejected(self):
        path = self.write_file("empty.pub", b"")
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_whitespace_only_file_is_rejected(self):
        path = self.write_file("ws.pub", b" \t\r\n\x0b\x0c   \n")
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_truncated_files_are_rejected(self):
        # Cuts at every interesting length: first bytes, mid header, payload
        # at various depths, missing END line.
        cut_points = [
            1,
            5,
            len(BEGIN),
            len(BEGIN) + 1,
            len(self.rsa_pem) // 3,
            len(self.rsa_pem) // 2,
            self.rsa_pem.index(END) - 1,
        ]
        for cut in cut_points:
            with self.subTest(cut=cut):
                path = self.write_file(f"trunc/{cut}.pub", self.rsa_pem[:cut])
                self.assertRejected(self.run_key_id(str(path)), path)

    def test_non_base64_character_in_payload_is_rejected(self):
        damaged = bytearray(self.rsa_pem)
        idx = self.rsa_pem.index(b"M")
        damaged[idx] = ord("!")
        path = self.write_file("badchar.pub", bytes(damaged))
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_base64_length_not_multiple_of_four_is_rejected(self):
        # Delete one payload character while keeping both boundary lines.
        body = self.rsa_pem.splitlines()
        payload = b"".join(body[1:-1])
        broken_payload = payload[:len(payload) // 2] + payload[len(payload) // 2 + 1:]
        content = BEGIN + b"\n" + broken_payload + b"\n" + END + b"\n"
        self.assertEqual(len(payload) % 4, 0)
        self.assertNotEqual(len(broken_payload) % 4, 0)
        path = self.write_file("badlen.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_noncanonical_padding_bits_are_rejected(self):
        encoded = base64.b64encode(self.ed_der)
        self.assertTrue(encoded.endswith(b"="))
        # Flip a low bit of the data character immediately before padding;
        # structurally well-formed base64 whose unused padding bits are set.
        broken = encoded[:-2] + bytes([encoded[-2] ^ 1]) + encoded[-1:]
        content = BEGIN + b"\n" + broken + b"\n" + END + b"\n"
        path = self.write_file("padbits.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_padding_before_final_quantum_is_rejected(self):
        encoded = bytearray(base64.b64encode(self.rsa_der))
        # Put '=' at position 2 of a quantum well inside the stream.
        self.assertEqual(10 % 4, 2)
        encoded[10] = ord("=")
        content = BEGIN + b"\n" + bytes(encoded) + b"\n" + END + b"\n"
        path = self.write_file("midpad.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_two_public_keys_are_rejected(self):
        path = self.write_file("two.pub", self.rsa_pem + self.ed_pem)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_second_block_after_end_is_rejected(self):
        trailing = self.rsa_pem + b"-----BEGIN PUBLIC KEY-----\n"
        path = self.write_file("second.pub", trailing)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_trailing_non_whitespace_is_rejected(self):
        for extra in (b"extra\n", b"x", b"\n-----\n", b"sha256:abcd\n"):
            with self.subTest(extra=extra):
                path = self.write_file("x.pub", self.rsa_pem + extra)
                self.assertRejected(self.run_key_id(str(path)), path)

    def test_leading_non_whitespace_is_rejected(self):
        for prefix in (b"junk\n", b"x" + self.rsa_pem, b"0" + self.rsa_pem):
            with self.subTest(prefix=prefix[:8]):
                path = self.write_file("x.pub", prefix)
                self.assertRejected(self.run_key_id(str(path)), path)

    def test_utf8_bom_is_rejected(self):
        path = self.write_file("bom.pub", b"\xef\xbb\xbf" + self.rsa_pem)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_non_ascii_byte_after_block_is_rejected(self):
        path = self.write_file("hi.pub", self.rsa_pem + b"\xff\n")
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_non_whitespace_glued_to_end_marker_is_rejected(self):
        # Whitespace relaxation starts only AFTER the complete marker: text
        # glued to its final '-' with no whitespace between is still invalid,
        # as is a truncated or internally misspelled marker followed by the
        # whitespace a complete marker would have accepted.
        block = wrap_public_pem(self.ed_der, 64, b"\n", final_newline=False)
        contents = [
            block + b"x",
            block + b" extra\n",
            block + b"-----",
            block + b" ",  # placeholder, replaced below with truncated marker
        ]
        contents[3] = block[: -len(END)] + END[:-1] + b" "
        contents.append(block[: -len(END)] + END[:-3] + b"   ")
        contents.append(
            block.replace(END, b"-----END  PUBLIC KEY-----", 1) + b" "
        )
        for i, content in enumerate(contents):
            with self.subTest(case=i):
                path = self.write_file(f"glued-bad/{i}.pub", content)
                self.assertRejected(self.run_key_id(str(path)), path)

    def test_text_on_end_line_is_rejected(self):
        content = self.rsa_pem.replace(END + b"\n", END + b" extra\n")
        path = self.write_file("endline.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_space_inside_payload_line_is_rejected(self):
        encoded = base64.b64encode(self.rsa_der)
        broken = encoded[:10] + b" " + encoded[10:]
        content = BEGIN + b"\n" + broken + b"\n" + END + b"\n"
        path = self.write_file("wspayload.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_blank_line_inside_block_is_rejected(self):
        encoded = base64.b64encode(self.rsa_der)
        head, tail = encoded[:64], encoded[64:]
        content = BEGIN + b"\n" + head + b"\n\n" + tail + b"\n" + END + b"\n"
        path = self.write_file("blank.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_begin_end_label_mismatch_is_rejected(self):
        content = self.rsa_pem.replace(
            END, b"-----END RSA PUBLIC KEY-----", 1
        )
        path = self.write_file("mismatch.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_other_begin_label_is_rejected(self):
        # Correct END marker but a different BEGIN label.
        content = self.rsa_pem.replace(
            BEGIN, b"-----BEGIN RSA PUBLIC KEY-----", 1
        )
        path = self.write_file("otherlabel.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_cr_only_line_endings_are_rejected(self):
        # Neither LF nor CRLF: bare CRs are not legal line separators here.
        content = self.rsa_pem.replace(b"\n", b"\r")
        path = self.write_file("cronly.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_pkcs8_private_key_is_rejected(self):
        pem = self.rsa_priv.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.PKCS8,
            serialization.NoEncryption(),
        )
        self.assertIn(b"PRIVATE KEY", pem)
        path = self.write_file("priv.pem", pem)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_pkcs1_rsa_private_key_is_rejected(self):
        pem = self.rsa_priv.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.TraditionalOpenSSL,
            serialization.NoEncryption(),
        )
        self.assertIn(b"RSA PRIVATE KEY", pem)
        path = self.write_file("rsa-priv.pem", pem)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_pkcs1_rsa_public_key_wrapper_is_rejected(self):
        # A valid RSA public key, but in the PKCS#1 wrapper rather than the
        # required SubjectPublicKeyInfo: fingerprinting it is forbidden.
        pem = self.rsa_pub.public_bytes(
            serialization.Encoding.PEM,
            serialization.PublicFormat.PKCS1,
        )
        self.assertIn(b"RSA PUBLIC KEY", pem)
        path = self.write_file("rsapkcs1.pub", pem)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_ec_private_key_is_rejected(self):
        pem = self.ec_priv.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.TraditionalOpenSSL,
            serialization.NoEncryption(),
        )
        self.assertIn(b"EC PRIVATE KEY", pem)
        path = self.write_file("ec-priv.pem", pem)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_certificate_is_rejected(self):
        name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, "test")])
        now = datetime.datetime(2026, 1, 1, tzinfo=datetime.timezone.utc)
        cert = (
            x509.CertificateBuilder()
            .subject_name(name)
            .issuer_name(name)
            .public_key(self.rsa_pub)
            .serial_number(1)
            .not_valid_before(now)
            .not_valid_after(now + datetime.timedelta(days=1))
            .sign(self.rsa_priv, hashes.SHA256())
        )
        pem = cert.public_bytes(serialization.Encoding.PEM)
        self.assertIn(b"CERTIFICATE", pem)
        path = self.write_file("cert.pem", pem)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_valid_key_with_garbage_appended_inside_encoding_rejected(self):
        # A second, incomplete PUBLIC KEY block glued before the END line.
        encoded = base64.b64encode(self.rsa_der)
        head, tail = encoded[:64], encoded[64:]
        content = (BEGIN + b"\n" + head + b"\n" + BEGIN + b"\n" + tail +
                   b"\n" + END + b"\n")
        path = self.write_file("nested.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_random_binary_is_rejected(self):
        path = self.write_file("rand.bin", bytes(range(256)) * 4)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_noncanonical_ber_length_is_rejected(self):
        # Ed25519 SPKI DER is short enough for a one-byte (short-form) outer
        # length; rewrite it as the non-minimal BER long form. The bytes still
        # parse as BER in many libraries but are not valid DER.
        self.assertEqual(self.ed_der[0], 0x30)
        self.assertLess(self.ed_der[1], 0x80)
        ber = bytes([0x30, 0x81, self.ed_der[1]]) + self.ed_der[2:]
        content = wrap_public_pem(ber)
        path = self.write_file("ber.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_trailing_bytes_after_der_are_rejected(self):
        # Valid SPKI followed by one extra byte inside the same PEM payload.
        broken_der = self.ed_der + b"\x00"
        content = wrap_public_pem(broken_der)
        path = self.write_file("trailing-der.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    # -- internal DER encoding (canonical SPKI only) -----------------------
    #
    # An intact PEM envelope -- correct PUBLIC KEY markers, legal base64, a
    # complete outer structure -- says nothing about whether the decoded
    # payload is canonical DER. The tests below pin that key-id rejects
    # non-canonical internal encodings (exit 1, empty stdout, stderr naming
    # the path) instead of normalizing them to a canonical re-encoding and
    # printing a fingerprint, while still accepting the one apparent oddity
    # DER itself requires: an RSA modulus' mandatory leading zero.

    def test_der_builders_reproduce_canonical_library_encoding(self):
        # Sanity for every internal-encoding test below: undisturbed, the
        # builders emit exactly the cryptography package's canonical DER,
        # and key-id accepts those hand-assembled bytes with the same
        # fingerprint as the library-produced PEM.
        self.assertEqual(self.rsa_hi_modulus_content[0], 0x00)
        self.assertGreaterEqual(self.rsa_hi_modulus_content[1], 0x80)
        rebuilt_rsa = build_rsa_spki_der(
            self.rsa_hi_modulus_content, self.rsa_hi_exponent_content
        )
        self.assertEqual(rebuilt_rsa, self.rsa_hi_der)
        rebuilt_ed = build_ed25519_spki_der(self.ed_raw)
        self.assertEqual(rebuilt_ed, self.ed_der)
        for name, der in (("rsa", rebuilt_rsa), ("ed25519", rebuilt_ed)):
            with self.subTest(name=name):
                path = self.write_file(
                    f"internal/rebuilt/{name}.pub", wrap_public_pem(der)
                )
                self.assertFingerprintOk(self.run_key_id(str(path)), der)

    def test_mandatory_leading_zero_modulus_is_accepted(self):
        # The flip side of rejecting surplus leading zeros: an RSA modulus
        # whose top bit is set MUST keep its 0x00 prefix -- that is the
        # canonical encoding, not an anomaly to be stripped. The fingerprint
        # is the SHA-256 of that exact DER under every legal PEM layout.
        expected = fingerprint_of_der(self.rsa_hi_der)
        variants = {
            "lf64.pub": wrap_public_pem(self.rsa_hi_der, 64, b"\n"),
            "crlf64.pub": wrap_public_pem(self.rsa_hi_der, 64, b"\r\n"),
            "lf17.pub": wrap_public_pem(self.rsa_hi_der, 17, b"\n"),
            "no-final-newline.pub": wrap_public_pem(
                self.rsa_hi_der, 64, b"\n", final_newline=False
            ),
        }
        for name, content in variants.items():
            with self.subTest(name=name):
                path = self.write_file(Path("internal/leading-zero", name),
                                       content)
                result = self.run_key_id(str(path))
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertEqual(result.stderr, b"")
                self.assertEqual(
                    result.stdout, (expected + "\n").encode("ascii")
                )

    def test_non_minimal_length_encodings_are_rejected(self):
        # Every length here still frames the same content bytes -- the key
        # material is untouched -- but the length-of-length is not the
        # shortest form DER requires. Re-encoding canonically and
        # fingerprinting the result is exactly what must NOT happen.
        mc, ec = self.rsa_hi_modulus_content, self.rsa_hi_exponent_content
        long_form = {"force_long_form": True}
        padded = {"extra_length_bytes": 1}
        variants = {
            # Canonically short-form lengths forced into long form.
            "rsa-algid-long-form":
                build_rsa_spki_der(mc, ec, algid=long_form),
            "rsa-exponent-long-form":
                build_rsa_spki_der(mc, ec, exponent=long_form),
            # Already long-form lengths with a superfluous zero length byte.
            "rsa-outer-padded-length":
                build_rsa_spki_der(mc, ec, outer=padded),
            "rsa-bit-string-padded-length":
                build_rsa_spki_der(mc, ec, bit_string=padded),
            "rsa-inner-padded-length":
                build_rsa_spki_der(mc, ec, inner=padded),
            "rsa-modulus-padded-length":
                build_rsa_spki_der(mc, ec, modulus=padded),
            # Every Ed25519 SPKI length is canonically short-form.
            "ed25519-outer-long-form":
                build_ed25519_spki_der(self.ed_raw, outer=long_form),
            "ed25519-algid-long-form":
                build_ed25519_spki_der(self.ed_raw, algid=long_form),
            "ed25519-bit-string-long-form":
                build_ed25519_spki_der(self.ed_raw, bit_string=long_form),
            "ed25519-outer-padded-length":
                build_ed25519_spki_der(self.ed_raw, outer=padded),
            # BER indefinite-length outer SEQUENCE terminated by an EOC.
            "rsa-outer-indefinite":
                b"\x30\x80" + der_content(build_rsa_spki_der(mc, ec))
                + b"\x00\x00",
            "ed25519-outer-indefinite":
                b"\x30\x80" + der_content(self.ed_der) + b"\x00\x00",
        }
        for name, der in variants.items():
            with self.subTest(name=name):
                self.assertNotEqual(der, self.rsa_hi_der)
                self.assertNotEqual(der, self.ed_der)
                path = self.write_file(f"internal/length/{name}.pub",
                                       wrap_public_pem(der))
                self.assertRejected(self.run_key_id(str(path)), path)

    def test_rsa_integer_extra_leading_zeros_are_rejected(self):
        # Surplus 0x00 prefixes on the modulus or exponent INTEGER: the
        # encoded integer value is unchanged (stripping the surplus bytes
        # recovers the canonical content exactly), but the encoding is not
        # DER and must be rejected, not normalized.
        mc, ec = self.rsa_hi_modulus_content, self.rsa_hi_exponent_content
        variants = {
            "modulus-one-extra-zero": build_rsa_spki_der(b"\x00" + mc, ec),
            "modulus-two-extra-zeros":
                build_rsa_spki_der(b"\x00\x00" + mc, ec),
            "exponent-one-extra-zero": build_rsa_spki_der(mc, b"\x00" + ec),
        }
        for name, der in variants.items():
            with self.subTest(name=name):
                self.assertNotEqual(der, self.rsa_hi_der)
                path = self.write_file(f"internal/int-zero/{name}.pub",
                                       wrap_public_pem(der))
                before = path.read_bytes()
                result = self.run_key_id(str(path))
                self.assertRejected(result, path)
                # Rejection is read-only: the input file is never rewritten
                # to a canonical encoding (or anything else).
                self.assertEqual(path.read_bytes(), before)

    def test_rsa_modulus_missing_mandatory_leading_zero_is_rejected(self):
        # Dropping the 0x00 from a top-bit-set modulus does not yield a
        # shorter encoding of the same key -- it makes the INTEGER negative.
        # This must not be "repaired" back into the canonical key either.
        truncated = self.rsa_hi_modulus_content[1:]
        self.assertGreaterEqual(truncated[0], 0x80)
        der = build_rsa_spki_der(truncated, self.rsa_hi_exponent_content)
        self.assertNotEqual(der, self.rsa_hi_der)
        path = self.write_file("internal/negative-modulus.pub",
                               wrap_public_pem(der))
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_declared_length_mismatching_content_is_rejected(self):
        # The outer SEQUENCE and the PEM envelope stay complete and
        # well-formed, but one inner field declares a length that does not
        # match its actual content. A parser that trusts the outer wrapper
        # alone would accept these; key-id must not.
        mc, ec = self.rsa_hi_modulus_content, self.rsa_hi_exponent_content
        variants = {
            "rsa-outer-declares-one-extra":
                build_rsa_spki_der(mc, ec, declared_delta=("outer", 1)),
            "rsa-outer-declares-one-less":
                build_rsa_spki_der(mc, ec, declared_delta=("outer", -1)),
            "rsa-bit-string-declares-one-extra":
                build_rsa_spki_der(mc, ec, declared_delta=("bit_string", 1)),
            "rsa-bit-string-declares-one-less":
                build_rsa_spki_der(mc, ec, declared_delta=("bit_string", -1)),
            "rsa-inner-declares-one-extra":
                build_rsa_spki_der(mc, ec, declared_delta=("inner", 1)),
            "rsa-inner-declares-one-less":
                build_rsa_spki_der(mc, ec, declared_delta=("inner", -1)),
            "rsa-modulus-declares-one-extra":
                build_rsa_spki_der(mc, ec, declared_delta=("modulus", 1)),
            "rsa-modulus-declares-one-less":
                build_rsa_spki_der(mc, ec, declared_delta=("modulus", -1)),
            "rsa-algid-declares-one-extra":
                build_rsa_spki_der(mc, ec, declared_delta=("algid", 1)),
            "rsa-algid-declares-one-less":
                build_rsa_spki_der(mc, ec, declared_delta=("algid", -1)),
            "ed25519-outer-declares-one-extra":
                build_ed25519_spki_der(self.ed_raw,
                                       declared_delta=("outer", 1)),
            "ed25519-outer-declares-one-less":
                build_ed25519_spki_der(self.ed_raw,
                                       declared_delta=("outer", -1)),
            "ed25519-bit-string-declares-one-extra":
                build_ed25519_spki_der(self.ed_raw,
                                       declared_delta=("bit_string", 1)),
            "ed25519-bit-string-declares-one-less":
                build_ed25519_spki_der(self.ed_raw,
                                       declared_delta=("bit_string", -1)),
            "ed25519-algid-declares-one-extra":
                build_ed25519_spki_der(self.ed_raw,
                                       declared_delta=("algid", 1)),
        }
        for name, der in variants.items():
            with self.subTest(name=name):
                self.assertNotEqual(der, self.rsa_hi_der)
                self.assertNotEqual(der, self.ed_der)
                path = self.write_file(f"internal/mismatch/{name}.pub",
                                       wrap_public_pem(der))
                self.assertRejected(self.run_key_id(str(path)), path)

    # -- file failures (exit code 1) -------------------------------------

    def test_nonexistent_path_fails_with_exit_code_1(self):
        missing = self.tmp / "目录" / "missing key.pub"
        self.assertFalse(missing.exists())
        result = self.run_key_id(str(missing))
        self.assertEqual(result.returncode, 1)
        self.assertEqual(result.stdout, b"")
        self.assertIn(os.fsencode(str(missing)), result.stderr)

    def test_directory_fails_with_exit_code_1(self):
        directory = self.tmp / "a directory"
        directory.mkdir()
        result = self.run_key_id(str(directory))
        self.assertEqual(result.returncode, 1)
        self.assertEqual(result.stdout, b"")
        self.assertIn(os.fsencode(str(directory)), result.stderr)

    @unittest.skipIf(
        hasattr(os, "geteuid") and os.geteuid() == 0,
        "root bypasses file permission bits",
    )
    def test_unreadable_file_fails_with_exit_code_1(self):
        path = self.write_file("secret.pub", self.rsa_pem)
        path.chmod(0o000)
        self.addCleanup(lambda: path.chmod(0o644))
        result = self.run_key_id(str(path))
        self.assertEqual(result.returncode, 1)
        self.assertEqual(result.stdout, b"")
        self.assertIn(os.fsencode(str(path)), result.stderr)

    # -- read failure after a successful open (exit code 1) -------------

    def _preload_env(self, **extra):
        env = dict(os.environ)
        preload = READFAIL_PRELOAD
        if env.get("LD_PRELOAD"):
            preload = preload + ":" + env["LD_PRELOAD"]
        env["LD_PRELOAD"] = preload
        env.update(extra)
        return env

    @requires_readfail_preload
    def test_read_error_after_partial_content_fails_with_exit_code_1(self):
        path = self.write_file(
            "readfail/key.pub", wrap_public_pem(self.rsa_der, 64, b"\n")
        )

        # Control: unarmed preload still succeeds.
        healthy = subprocess.run(
            [SEALMARK_BIN, "key-id", str(path)],
            capture_output=True,
            env=self._preload_env(SEALMARK_READFAIL_PATH=str(path)),
        )
        self.assertEqual(healthy.returncode, 0, healthy.stderr)

        size = path.stat().st_size
        for after in (1, 100, size // 2, size - 1):
            with self.subTest(after=after):
                result = subprocess.run(
                    [SEALMARK_BIN, "key-id", str(path)],
                    capture_output=True,
                    env=self._preload_env(
                        SEALMARK_READFAIL_PATH=str(path),
                        SEALMARK_READFAIL_AFTER=str(after),
                    ),
                )
                self.assertEqual(result.returncode, 1, result.stderr)
                self.assertEqual(result.stdout, b"")
                self.assertIn(b"read", result.stderr.lower())
                self.assertIn(os.fsencode(str(path)), result.stderr)
                self.assertNotIn(b"spki-sha256", result.stderr)

    # -- usage errors (exit code 2) --------------------------------------

    def assertUsageError(self, result):
        self.assertEqual(result.returncode, 2)
        self.assertEqual(result.stdout, b"")
        self.assertIn(b"Usage", result.stderr)
        self.assertIn(b"key-id", result.stderr)
        self.assertTrue(result.stderr.endswith(b"\n"))

    def test_missing_path_argument_is_usage_error(self):
        self.assertUsageError(self.run_sealmark("key-id"))

    def test_empty_path_argument_is_usage_error(self):
        self.assertUsageError(self.run_sealmark("key-id", ""))

    def test_extra_argument_is_usage_error(self):
        path = self.write_file("ed.pub", self.ed_pem)
        self.assertUsageError(
            self.run_sealmark("key-id", str(path), "extra")
        )

    def test_no_arguments_is_usage_error(self):
        result = self.run_sealmark()
        self.assertEqual(result.returncode, 2)
        self.assertEqual(result.stdout, b"")

    # -- pre-existing features kept compatible ---------------------------

    def test_version_output_unchanged(self):
        result = self.run_sealmark("--version")
        self.assertEqual(result.returncode, 0)
        self.assertEqual(result.stderr, b"")
        self.assertEqual(result.stdout, b"sealmark 0.1.0\n")

    def test_digest_still_hashes_raw_bytes_not_parsed_key(self):
        # digest's result must remain the raw-byte digest, which differs from
        # the key fingerprint and changes when the PEM is re-wrapped.
        path = self.write_file("ed.pub", self.ed_pem)
        rewrapped = self.write_file(
            "ed-rewrapped.pub", wrap_public_pem(self.ed_der, 10, b"\r\n")
        )
        d1 = self.run_sealmark("digest", str(path))
        d2 = self.run_sealmark("digest", str(rewrapped))
        k1 = self.run_key_id(str(path))
        self.assertEqual(d1.returncode, 0, d1.stderr)
        self.assertEqual(d2.returncode, 0, d2.stderr)
        self.assertNotEqual(d1.stdout, d2.stdout)  # layout changes raw digest
        self.assertEqual(
            d1.stdout,
            b"sha256:" + hashlib.sha256(self.ed_pem).hexdigest().encode()
            + b"\n",
        )
        self.assertNotEqual(k1.stdout, d1.stdout)


if __name__ == "__main__":
    unittest.main(verbosity=2)
