#!/usr/bin/env python3
"""Regression tests for ``sealmark key-id``.

The key-id contract under test (see README):

* success: exit code 0, empty stderr, stdout is exactly one line
  ``spki-sha256:<64 lowercase hex digits>`` terminated by a single newline;
* the fingerprint is the SHA-256 of the SubjectPublicKeyInfo DER carried by
  the PEM block -- the public-key algorithm identifier and public key value
  are included; file name, path and the PEM text layout are not;
* at least RSA and Ed25519 SubjectPublicKeyInfo public keys are supported
  (EC P-256 is covered as well);
* the same key produces the same fingerprint under LF or CRLF line endings,
  any legal base64 line wrapping, no trailing newline, and after the file is
  moved or renamed;
* the fingerprint is independently recomputed here with hashlib over the DER
  obtained from the cryptography package, and one Ed25519 case is pinned to a
  known answer;
* the file must contain exactly one PEM block wrapped in the literal
  ``PUBLIC KEY`` label, with only ASCII whitespace before or after it. Empty
  files, damaged/truncated encodings, non-canonical base64, more than one key,
  stray non-whitespace bytes, private keys, certificates and other public-key
  wrappers (e.g. PKCS#1 ``RSA PUBLIC KEY``) all fail;
* missing path / directory / unreadable input / invalid key content: exit
  code 1 with empty stdout and a stderr message containing the path -- the
  command never falls back to a file digest and never prints a partial
  fingerprint;
* missing/empty/extra arguments: exit code 2, empty stdout, usage text on
  stderr mentioning ``key-id``;
* the file is consumed in fixed-size read passes (CHUNK_SIZE bytes): legal
  ASCII whitespace that pushes the block across pass boundaries, BEGIN/END
  markers, base64 lines and CRLF pairs split between two passes, an END
  marker ending exactly at end of file, distant trailing junk behind large
  whitespace, and truncation landing on a pass boundary are all covered.

The read-failure cases reuse the LD_PRELOAD fault injector shared with the
other suites ($SEALMARK_READFAIL_PRELOAD): a regular file opens fine and
read() then fails with EIO after an exact number of delivered bytes. Those
tests skip when the injector is unavailable. Key material and all files are
generated by the tests themselves inside a fresh temporary directory.
"""

import base64
import datetime
import hashlib
import os
import re
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec, ed25519, rsa
from cryptography.x509.oid import NameOID

# Must match the read buffer size in src/main.cpp.
CHUNK_SIZE = 64 * 1024

SEALMARK_BIN = os.environ.get("SEALMARK_BIN")
READFAIL_PRELOAD = os.environ.get("SEALMARK_READFAIL_PRELOAD")

requires_readfail_preload = unittest.skipUnless(
    READFAIL_PRELOAD and Path(READFAIL_PRELOAD).is_file(),
    "SEALMARK_READFAIL_PRELOAD is unavailable; mid-read failure cannot be "
    "injected on this platform",
)

OUTPUT_RE = re.compile(rb"\Aspki-sha256:[0-9a-f]{64}\n\Z")

# SubjectPublicKeyInfo DER of the Ed25519 public key derived from the
# all-zero 32-byte private scalar, pinned so the wire value itself is
# regression-tested (not just self-consistency between runs).
ED25519_ZERO_SPKI_DER = bytes.fromhex(
    "302a300506032b65700321003b6a27bcceb6a42d62a3a8d02a6f0d7365321577"
    "1de243a63ac048a18b59da29"
)
ED25519_ZERO_FINGERPRINT = (
    "spki-sha256:339e2ff917630507b6a423b5ce084e285d1fa65d93b3e27a6195d3bbebc9ae23"
)

BEGIN = b"-----BEGIN PUBLIC KEY-----"
END = b"-----END PUBLIC KEY-----"


def spki_der(pub):
    return pub.public_bytes(
        serialization.Encoding.DER,
        serialization.PublicFormat.SubjectPublicKeyInfo,
    )


def fingerprint_of_der(der):
    return "spki-sha256:" + hashlib.sha256(der).hexdigest()


def wrap_public_pem(der, width=64, newline=b"\n", final_newline=True,
                    begin=BEGIN, end=END):
    """Build a PUBLIC KEY PEM with explicit control over its text layout."""
    encoded = base64.b64encode(der)
    lines = [encoded[i:i + width] for i in range(0, len(encoded), width)]
    out = begin + newline + newline.join(lines) + newline + end
    if final_newline:
        out += newline
    return out


def ascii_whitespace(length):
    """A deterministic mix of every permitted ASCII whitespace byte."""
    cycle = b" \t\r\n\x0b\x0c"
    return (cycle * (length // len(cycle) + 1))[:length]


class SealmarkKeyIdTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        if not SEALMARK_BIN:
            raise RuntimeError(
                "SEALMARK_BIN is not set; point it at the sealmark executable"
            )
        if not Path(SEALMARK_BIN).is_file():
            raise RuntimeError(f"SEALMARK_BIN does not point to a file: {SEALMARK_BIN}")

        cls.rsa_priv = rsa.generate_private_key(public_exponent=65537,
                                                key_size=2048)
        cls.rsa_pub = cls.rsa_priv.public_key()
        cls.rsa_der = spki_der(cls.rsa_pub)
        cls.rsa_pem = cls.rsa_pub.public_bytes(
            serialization.Encoding.PEM,
            serialization.PublicFormat.SubjectPublicKeyInfo,
        )

        cls.ed_priv = ed25519.Ed25519PrivateKey.generate()
        cls.ed_pub = cls.ed_priv.public_key()
        cls.ed_der = spki_der(cls.ed_pub)
        cls.ed_pem = cls.ed_pub.public_bytes(
            serialization.Encoding.PEM,
            serialization.PublicFormat.SubjectPublicKeyInfo,
        )

        cls.other_ed_priv = ed25519.Ed25519PrivateKey.generate()
        cls.other_ed_der = spki_der(cls.other_ed_priv.public_key())

        cls.ec_priv = ec.generate_private_key(ec.SECP256R1())
        cls.ec_der = spki_der(cls.ec_priv.public_key())

    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="sealmark-keyid-test-"))
        self.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)

    def run_sealmark(self, *args):
        return subprocess.run([SEALMARK_BIN, *args], capture_output=True)

    def run_key_id(self, path_arg):
        return self.run_sealmark("key-id", path_arg)

    def write_file(self, relative_path, content):
        path = self.tmp / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
        return path

    def assertFingerprintOk(self, result, der):
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stderr, b"")
        self.assertRegex(result.stdout, OUTPUT_RE)
        self.assertEqual(len(result.stdout), len("spki-sha256:") + 64 + 1)
        self.assertEqual(
            result.stdout,
            (fingerprint_of_der(der) + "\n").encode("ascii"),
        )

    def assertRejected(self, result, path):
        self.assertEqual(result.returncode, 1, result.stderr)
        self.assertEqual(result.stdout, b"")
        self.assertIn(os.fsencode(str(path)), result.stderr)
        self.assertNotIn(b"spki-sha256", result.stderr)
        self.assertNotIn(b"Usage", result.stderr)
        self.assertTrue(result.stderr.endswith(b"\n"))

    # -- success ---------------------------------------------------------

    def test_rsa_fingerprint_is_sha256_of_spki_der(self):
        path = self.write_file("rsa.pub", self.rsa_pem)
        self.assertFingerprintOk(self.run_key_id(str(path)), self.rsa_der)

    def test_ed25519_fingerprint_is_sha256_of_spki_der(self):
        path = self.write_file("ed25519.pub", self.ed_pem)
        self.assertFingerprintOk(self.run_key_id(str(path)), self.ed_der)

    def test_ec_p256_fingerprint_is_sha256_of_spki_der(self):
        pem = self.ec_priv.public_key().public_bytes(
            serialization.Encoding.PEM,
            serialization.PublicFormat.SubjectPublicKeyInfo,
        )
        path = self.write_file("ec.pub", pem)
        self.assertFingerprintOk(self.run_key_id(str(path)), self.ec_der)

    def test_ed25519_known_answer(self):
        zero_priv = ed25519.Ed25519PrivateKey.from_private_bytes(b"\x00" * 32)
        zero_pub = zero_priv.public_key()
        self.assertEqual(spki_der(zero_pub), ED25519_ZERO_SPKI_DER)
        path = self.write_file(
            "zero-ed.pub",
            zero_pub.public_bytes(
                serialization.Encoding.PEM,
                serialization.PublicFormat.SubjectPublicKeyInfo,
            ),
        )

        result = self.run_key_id(str(path))

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stderr, b"")
        self.assertEqual(
            result.stdout, (ED25519_ZERO_FINGERPRINT + "\n").encode("ascii")
        )

    def test_lf_crlf_and_any_base64_wrapping_give_same_fingerprint(self):
        expected = fingerprint_of_der(self.rsa_der)
        variants = {
            "lf64.pub": wrap_public_pem(self.rsa_der, 64, b"\n"),
            "crlf64.pub": wrap_public_pem(self.rsa_der, 64, b"\r\n"),
            "lf1.pub": wrap_public_pem(self.rsa_der, 1, b"\n"),
            "crlf4.pub": wrap_public_pem(self.rsa_der, 4, b"\r\n"),
            "lf73.pub": wrap_public_pem(self.rsa_der, 73, b"\n"),
            "single_line.pub": wrap_public_pem(
                self.rsa_der, len(base64.b64encode(self.rsa_der)), b"\n"
            ),
            "no_final_newline.pub":
                wrap_public_pem(self.rsa_der, 64, b"\n", final_newline=False),
            "crlf_no_final_newline.pub":
                wrap_public_pem(self.rsa_der, 64, b"\r\n", final_newline=False),
        }
        seen = set()
        for name, content in variants.items():
            with self.subTest(name=name):
                path = self.write_file(Path("wrap", name), content)
                result = self.run_key_id(str(path))
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertEqual(result.stderr, b"")
                self.assertEqual(
                    result.stdout, (expected + "\n").encode("ascii")
                )
                seen.add(result.stdout)
        # All layouts of the same key collapse to one fingerprint.
        self.assertEqual(seen, {(expected + "\n").encode("ascii")})

    def test_ascii_whitespace_around_block_is_ignored(self):
        expected = fingerprint_of_der(self.ed_der)
        ws = b" \t\r\n\x0b\x0c"
        variants = [
            ws + self.ed_pem,
            self.ed_pem + ws,
            ws + self.ed_pem + ws,
            b"\n" + self.ed_pem,
            self.ed_pem.replace(b"\n", b"\r\n") + b"\n",
        ]
        for i, content in enumerate(variants):
            with self.subTest(variant=i):
                path = self.write_file(f"ws/{i}.pub", content)
                result = self.run_key_id(str(path))
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertEqual(result.stderr, b"")
                self.assertEqual(
                    result.stdout, (expected + "\n").encode("ascii")
                )

    def test_move_and_rename_do_not_change_fingerprint(self):
        names = [
            "key.pub",
            "nested/dir/public key.pub",
            "目录/公钥 副本.pub",
            "deep/deeper/key 0.tmp",
        ]
        outputs = set()
        for name in names:
            with self.subTest(name=name):
                path = self.write_file(Path(name), self.ed_pem)
                result = self.run_key_id(str(path))
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertEqual(result.stderr, b"")
                outputs.add(result.stdout)
        self.assertEqual(len(outputs), 1)
        self.assertEqual(
            outputs.pop(),
            (fingerprint_of_der(self.ed_der) + "\n").encode("ascii"),
        )

    def test_different_keys_have_different_fingerprints(self):
        self.assertNotEqual(self.ed_der, self.other_ed_der)
        p1 = self.write_file("a.pub", self.ed_pem)
        p2 = self.write_file(
            "b.pub",
            self.other_ed_priv.public_key().public_bytes(
                serialization.Encoding.PEM,
                serialization.PublicFormat.SubjectPublicKeyInfo,
            ),
        )
        r1 = self.run_key_id(str(p1))
        r2 = self.run_key_id(str(p2))
        self.assertEqual(r1.returncode, 0, r1.stderr)
        self.assertEqual(r2.returncode, 0, r2.stderr)
        self.assertNotEqual(r1.stdout, r2.stdout)
        self.assertEqual(
            r1.stdout,
            (fingerprint_of_der(self.ed_der) + "\n").encode("ascii"),
        )
        self.assertEqual(
            r2.stdout,
            (fingerprint_of_der(self.other_ed_der) + "\n").encode("ascii"),
        )

    def test_input_file_is_not_modified(self):
        path = self.write_file("rsa.pub", self.rsa_pem)
        before = path.stat()
        content_before = path.read_bytes()
        result = self.run_key_id(str(path))
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(path.read_bytes(), content_before)
        self.assertEqual(path.stat().st_size, before.st_size)

    # -- invalid content (exit code 1) -----------------------------------

    def test_empty_file_is_rejected(self):
        path = self.write_file("empty.pub", b"")
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_whitespace_only_file_is_rejected(self):
        path = self.write_file("ws.pub", b" \t\r\n\x0b\x0c   \n")
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_truncated_files_are_rejected(self):
        # Cuts at every interesting length: first bytes, mid header, payload
        # at various depths, missing END line.
        cut_points = [
            1,
            5,
            len(BEGIN),
            len(BEGIN) + 1,
            len(self.rsa_pem) // 3,
            len(self.rsa_pem) // 2,
            self.rsa_pem.index(END) - 1,
        ]
        for cut in cut_points:
            with self.subTest(cut=cut):
                path = self.write_file(f"trunc/{cut}.pub", self.rsa_pem[:cut])
                self.assertRejected(self.run_key_id(str(path)), path)

    def test_non_base64_character_in_payload_is_rejected(self):
        damaged = bytearray(self.rsa_pem)
        idx = self.rsa_pem.index(b"M")
        damaged[idx] = ord("!")
        path = self.write_file("badchar.pub", bytes(damaged))
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_base64_length_not_multiple_of_four_is_rejected(self):
        # Delete one payload character while keeping both boundary lines.
        body = self.rsa_pem.splitlines()
        payload = b"".join(body[1:-1])
        broken_payload = payload[:len(payload) // 2] + payload[len(payload) // 2 + 1:]
        content = BEGIN + b"\n" + broken_payload + b"\n" + END + b"\n"
        self.assertEqual(len(payload) % 4, 0)
        self.assertNotEqual(len(broken_payload) % 4, 0)
        path = self.write_file("badlen.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_noncanonical_padding_bits_are_rejected(self):
        encoded = base64.b64encode(self.ed_der)
        self.assertTrue(encoded.endswith(b"="))
        # Flip a low bit of the data character immediately before padding;
        # structurally well-formed base64 whose unused padding bits are set.
        broken = encoded[:-2] + bytes([encoded[-2] ^ 1]) + encoded[-1:]
        content = BEGIN + b"\n" + broken + b"\n" + END + b"\n"
        path = self.write_file("padbits.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_padding_before_final_quantum_is_rejected(self):
        encoded = bytearray(base64.b64encode(self.rsa_der))
        # Put '=' at position 2 of a quantum well inside the stream.
        self.assertEqual(10 % 4, 2)
        encoded[10] = ord("=")
        content = BEGIN + b"\n" + bytes(encoded) + b"\n" + END + b"\n"
        path = self.write_file("midpad.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_two_public_keys_are_rejected(self):
        path = self.write_file("two.pub", self.rsa_pem + self.ed_pem)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_second_block_after_end_is_rejected(self):
        trailing = self.rsa_pem + b"-----BEGIN PUBLIC KEY-----\n"
        path = self.write_file("second.pub", trailing)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_trailing_non_whitespace_is_rejected(self):
        for extra in (b"extra\n", b"x", b"\n-----\n", b"sha256:abcd\n"):
            with self.subTest(extra=extra):
                path = self.write_file("x.pub", self.rsa_pem + extra)
                self.assertRejected(self.run_key_id(str(path)), path)

    def test_leading_non_whitespace_is_rejected(self):
        for prefix in (b"junk\n", b"x" + self.rsa_pem, b"0" + self.rsa_pem):
            with self.subTest(prefix=prefix[:8]):
                path = self.write_file("x.pub", prefix)
                self.assertRejected(self.run_key_id(str(path)), path)

    def test_utf8_bom_is_rejected(self):
        path = self.write_file("bom.pub", b"\xef\xbb\xbf" + self.rsa_pem)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_non_ascii_byte_after_block_is_rejected(self):
        path = self.write_file("hi.pub", self.rsa_pem + b"\xff\n")
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_text_on_end_line_is_rejected(self):
        content = self.rsa_pem.replace(END + b"\n", END + b" extra\n")
        path = self.write_file("endline.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_space_inside_payload_line_is_rejected(self):
        encoded = base64.b64encode(self.rsa_der)
        broken = encoded[:10] + b" " + encoded[10:]
        content = BEGIN + b"\n" + broken + b"\n" + END + b"\n"
        path = self.write_file("wspayload.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_blank_line_inside_block_is_rejected(self):
        encoded = base64.b64encode(self.rsa_der)
        head, tail = encoded[:64], encoded[64:]
        content = BEGIN + b"\n" + head + b"\n\n" + tail + b"\n" + END + b"\n"
        path = self.write_file("blank.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_begin_end_label_mismatch_is_rejected(self):
        content = self.rsa_pem.replace(
            END, b"-----END RSA PUBLIC KEY-----", 1
        )
        path = self.write_file("mismatch.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_other_begin_label_is_rejected(self):
        # Correct END marker but a different BEGIN label.
        content = self.rsa_pem.replace(
            BEGIN, b"-----BEGIN RSA PUBLIC KEY-----", 1
        )
        path = self.write_file("otherlabel.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_cr_only_line_endings_are_rejected(self):
        # Neither LF nor CRLF: bare CRs are not legal line separators here.
        content = self.rsa_pem.replace(b"\n", b"\r")
        path = self.write_file("cronly.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_pkcs8_private_key_is_rejected(self):
        pem = self.rsa_priv.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.PKCS8,
            serialization.NoEncryption(),
        )
        self.assertIn(b"PRIVATE KEY", pem)
        path = self.write_file("priv.pem", pem)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_pkcs1_rsa_private_key_is_rejected(self):
        pem = self.rsa_priv.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.TraditionalOpenSSL,
            serialization.NoEncryption(),
        )
        self.assertIn(b"RSA PRIVATE KEY", pem)
        path = self.write_file("rsa-priv.pem", pem)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_pkcs1_rsa_public_key_wrapper_is_rejected(self):
        # A valid RSA public key, but in the PKCS#1 wrapper rather than the
        # required SubjectPublicKeyInfo: fingerprinting it is forbidden.
        pem = self.rsa_pub.public_bytes(
            serialization.Encoding.PEM,
            serialization.PublicFormat.PKCS1,
        )
        self.assertIn(b"RSA PUBLIC KEY", pem)
        path = self.write_file("rsapkcs1.pub", pem)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_ec_private_key_is_rejected(self):
        pem = self.ec_priv.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.TraditionalOpenSSL,
            serialization.NoEncryption(),
        )
        self.assertIn(b"EC PRIVATE KEY", pem)
        path = self.write_file("ec-priv.pem", pem)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_certificate_is_rejected(self):
        name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, "test")])
        now = datetime.datetime(2026, 1, 1, tzinfo=datetime.timezone.utc)
        cert = (
            x509.CertificateBuilder()
            .subject_name(name)
            .issuer_name(name)
            .public_key(self.rsa_pub)
            .serial_number(1)
            .not_valid_before(now)
            .not_valid_after(now + datetime.timedelta(days=1))
            .sign(self.rsa_priv, hashes.SHA256())
        )
        pem = cert.public_bytes(serialization.Encoding.PEM)
        self.assertIn(b"CERTIFICATE", pem)
        path = self.write_file("cert.pem", pem)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_valid_key_with_garbage_appended_inside_encoding_rejected(self):
        # A second, incomplete PUBLIC KEY block glued before the END line.
        encoded = base64.b64encode(self.rsa_der)
        head, tail = encoded[:64], encoded[64:]
        content = (BEGIN + b"\n" + head + b"\n" + BEGIN + b"\n" + tail +
                   b"\n" + END + b"\n")
        path = self.write_file("nested.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_random_binary_is_rejected(self):
        path = self.write_file("rand.bin", bytes(range(256)) * 4)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_noncanonical_ber_length_is_rejected(self):
        # Ed25519 SPKI DER is short enough for a one-byte (short-form) outer
        # length; rewrite it as the non-minimal BER long form. The bytes still
        # parse as BER in many libraries but are not valid DER.
        self.assertEqual(self.ed_der[0], 0x30)
        self.assertLess(self.ed_der[1], 0x80)
        ber = bytes([0x30, 0x81, self.ed_der[1]]) + self.ed_der[2:]
        content = wrap_public_pem(ber)
        path = self.write_file("ber.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_trailing_bytes_after_der_are_rejected(self):
        # Valid SPKI followed by one extra byte inside the same PEM payload.
        broken_der = self.ed_der + b"\x00"
        content = wrap_public_pem(broken_der)
        path = self.write_file("trailing-der.pub", content)
        self.assertRejected(self.run_key_id(str(path)), path)

    # -- multi-read (chunk-boundary) coverage ------------------------------
    #
    # The file is read in CHUNK_SIZE-byte passes. These tests pin the
    # behaviour of inputs whose PEM block, surrounding whitespace or
    # trailing content crosses one or more read boundaries: legal layout
    # must not change the fingerprint no matter where a pass boundary
    # falls, and the whole-file validity check must extend to the very
    # last read rather than stopping at the first complete key.

    def test_large_whitespace_around_block_spanning_reads_same_fingerprint(self):
        keys = {
            "rsa": (self.rsa_der, self.rsa_pem),
            "ed25519": (self.ed_der, self.ed_pem),
        }
        for key_name, (der, pem) in keys.items():
            expected = (fingerprint_of_der(der) + "\n").encode("ascii")
            variants = {
                "before": ascii_whitespace(3 * CHUNK_SIZE + 7) + pem,
                "after": pem + ascii_whitespace(2 * CHUNK_SIZE + 13),
                "both": (ascii_whitespace(CHUNK_SIZE + 1) + pem +
                         ascii_whitespace(CHUNK_SIZE - 1)),
            }
            for variant, content in variants.items():
                with self.subTest(key=key_name, variant=variant):
                    self.assertGreater(len(content), CHUNK_SIZE)
                    path = self.write_file(
                        f"multi-ws/{key_name}-{variant}.pub", content
                    )
                    result = self.run_key_id(str(path))
                    self.assertEqual(result.returncode, 0, result.stderr)
                    self.assertEqual(result.stderr, b"")
                    self.assertEqual(result.stdout, expected)

    def test_pem_structure_split_across_read_boundary_same_fingerprint(self):
        pem = self.rsa_pem
        end_at = pem.index(END)
        # Each offset is placed exactly on a read boundary, so the bytes
        # before it and from it onward arrive in different read passes.
        offsets = {
            "begin-start": 1,
            "begin-mid": len(BEGIN) // 2,
            "begin-last": len(BEGIN) - 1,
            "begin-line-feed": len(BEGIN),
            "first-payload-byte": len(BEGIN) + 1,
            "payload-mid": (len(BEGIN) + end_at) // 2,
            "payload-line-feed": pem.index(b"\n", len(BEGIN) + 2),
            "end-start": end_at + 1,
            "end-mid": end_at + len(END) // 2,
            "end-last": end_at + len(END) - 1,
            "final-newline": len(pem) - 1,
        }
        expected = (fingerprint_of_der(self.rsa_der) + "\n").encode("ascii")
        for name, off in offsets.items():
            for target in (CHUNK_SIZE, 2 * CHUNK_SIZE):
                with self.subTest(name=name, target=target):
                    content = ascii_whitespace(target - off) + pem
                    self.assertGreater(len(content), target)
                    path = self.write_file(
                        f"split/{target}-{name}.pub", content
                    )
                    result = self.run_key_id(str(path))
                    self.assertEqual(result.returncode, 0, result.stderr)
                    self.assertEqual(result.stderr, b"")
                    self.assertEqual(result.stdout, expected)

    def test_crlf_pair_split_across_read_boundary_same_fingerprint(self):
        pem = self.rsa_pem.replace(b"\n", b"\r\n")
        # Offsets of the LF byte of CRLF pairs: the CR then arrives at the
        # end of one read pass and the LF at the start of the next.
        header_lf = pem.index(b"\r\n") + 1
        payload_lf = pem.index(b"\r\n", header_lf + 1) + 1
        end_line_lf = pem.rindex(b"\r\n") + 1
        offsets = {
            "header-crlf": header_lf,
            "payload-crlf": payload_lf,
            "end-line-crlf": end_line_lf,
            "begin-mid": len(BEGIN) // 2,
            "end-mid": pem.index(END) + len(END) // 2,
        }
        expected = (fingerprint_of_der(self.rsa_der) + "\n").encode("ascii")
        for name, off in offsets.items():
            with self.subTest(name=name):
                content = ascii_whitespace(CHUNK_SIZE - off) + pem
                self.assertGreater(len(content), CHUNK_SIZE)
                path = self.write_file(f"split-crlf/{name}.pub", content)
                result = self.run_key_id(str(path))
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertEqual(result.stderr, b"")
                self.assertEqual(result.stdout, expected)

    def test_base64_rewrapping_with_large_whitespace_same_fingerprint(self):
        encoded_len = len(base64.b64encode(self.rsa_der))
        variants = [
            wrap_public_pem(self.rsa_der, 1, b"\n"),
            wrap_public_pem(self.rsa_der, 4, b"\r\n"),
            wrap_public_pem(self.rsa_der, 63, b"\n"),
            wrap_public_pem(self.rsa_der, 64, b"\n"),
            wrap_public_pem(self.rsa_der, 65, b"\r\n"),
            wrap_public_pem(self.rsa_der, encoded_len, b"\n"),
        ]
        expected = (fingerprint_of_der(self.rsa_der) + "\n").encode("ascii")
        outputs = set()
        for i, pem in enumerate(variants):
            with self.subTest(variant=i):
                content = (ascii_whitespace(CHUNK_SIZE + 3 * i) + pem +
                           ascii_whitespace(CHUNK_SIZE + 5))
                self.assertGreater(len(content), 2 * CHUNK_SIZE)
                path = self.write_file(f"rewrap/{i}.pub", content)
                result = self.run_key_id(str(path))
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertEqual(result.stderr, b"")
                self.assertEqual(result.stdout, expected)
                outputs.add(result.stdout)
        self.assertEqual(outputs, {expected})

    def test_content_beyond_large_trailing_whitespace_is_rejected(self):
        gap = ascii_whitespace(2 * CHUNK_SIZE + 5)
        cases = {
            # A second key (or any other content) far behind the first one
            # must reject the whole file; the first key's fingerprint may
            # never be printed before the rest is checked.
            "second-key": self.rsa_pem + gap + self.ed_pem,
            "same-key-twice": self.rsa_pem + gap + self.rsa_pem,
            "begin-marker": self.rsa_pem + gap + BEGIN + b"\n",
            "non-ws-byte": self.rsa_pem + gap + b"x",
            "non-ascii-byte": self.rsa_pem + gap + b"\xff",
            "junk-before": b"x" + gap + self.rsa_pem,
        }
        for name, content in cases.items():
            with self.subTest(name=name):
                self.assertGreater(len(content), 2 * CHUNK_SIZE)
                path = self.write_file(f"distant/{name}.pub", content)
                result = self.run_key_id(str(path))
                self.assertRejected(result, path)
                self.assertIn(b"valid", result.stderr)

    def test_whitespace_only_file_spanning_reads_is_rejected(self):
        path = self.write_file(
            "ws-only.pub", ascii_whitespace(2 * CHUNK_SIZE + 3)
        )
        self.assertRejected(self.run_key_id(str(path)), path)

    def test_truncation_at_read_boundary_is_rejected(self):
        pem = self.rsa_pem
        end_at = pem.index(END)
        # Each cut leaves the file ending mid-structure exactly on a read
        # boundary: inside BEGIN, right after the BEGIN line, mid base64,
        # or inside END.
        cuts = {
            "inside-begin": len(BEGIN) // 2,
            "begin-almost-complete": len(BEGIN) - 1,
            "after-begin-line": len(BEGIN) + 1,
            "mid-payload": (len(BEGIN) + end_at) // 2,
            "payload-near-end": end_at - 2,
            "inside-end": end_at + len(END) // 2,
            "end-almost-complete": end_at + len(END) - 1,
        }
        for name, cut in cuts.items():
            for target in (CHUNK_SIZE, 2 * CHUNK_SIZE):
                with self.subTest(name=name, target=target):
                    content = ascii_whitespace(target - cut) + pem[:cut]
                    self.assertEqual(len(content), target)
                    path = self.write_file(f"cut/{target}-{name}.pub", content)
                    self.assertRejected(self.run_key_id(str(path)), path)

    def test_end_marker_at_eof_without_newline_is_valid(self):
        pems = {
            "lf": wrap_public_pem(self.rsa_der, 64, b"\n",
                                  final_newline=False),
            "crlf": wrap_public_pem(self.rsa_der, 64, b"\r\n",
                                    final_newline=False),
        }
        expected = (fingerprint_of_der(self.rsa_der) + "\n").encode("ascii")
        for name, pem in pems.items():
            # The END marker's last byte is the file's last byte, exactly on
            # and around read boundaries; no trailing newline needed.
            for target in (CHUNK_SIZE, 2 * CHUNK_SIZE, 2 * CHUNK_SIZE + 17):
                with self.subTest(name=name, target=target):
                    content = ascii_whitespace(target - len(pem)) + pem
                    self.assertEqual(len(content), target)
                    path = self.write_file(f"eof/{name}-{target}.pub", content)
                    result = self.run_key_id(str(path))
                    self.assertEqual(result.returncode, 0, result.stderr)
                    self.assertEqual(result.stderr, b"")
                    self.assertEqual(result.stdout, expected)

    def test_end_at_eof_and_newline_plus_whitespace_same_fingerprint(self):
        bare = wrap_public_pem(self.ed_der, 64, b"\n", final_newline=False)
        prefix = ascii_whitespace(CHUNK_SIZE - len(bare))
        # END's last byte lands exactly at the first read boundary...
        at_eof = prefix + bare
        # ...and the same key with a legal final newline plus a further
        # read's worth of trailing whitespace.
        with_tail = prefix + bare + b"\n" + ascii_whitespace(CHUNK_SIZE)
        self.assertEqual(len(at_eof), CHUNK_SIZE)

        p1 = self.write_file("eof/bare.pub", at_eof)
        p2 = self.write_file("eof/with-tail.pub", with_tail)
        r1 = self.run_key_id(str(p1))
        r2 = self.run_key_id(str(p2))
        self.assertEqual(r1.returncode, 0, r1.stderr)
        self.assertEqual(r2.returncode, 0, r2.stderr)
        self.assertEqual(r1.stderr, b"")
        self.assertEqual(r2.stderr, b"")
        self.assertEqual(r1.stdout, r2.stdout)
        self.assertEqual(
            r1.stdout,
            (fingerprint_of_der(self.ed_der) + "\n").encode("ascii"),
        )

    # -- file failures (exit code 1) -------------------------------------

    def test_nonexistent_path_fails_with_exit_code_1(self):
        missing = self.tmp / "目录" / "missing key.pub"
        self.assertFalse(missing.exists())
        result = self.run_key_id(str(missing))
        self.assertEqual(result.returncode, 1)
        self.assertEqual(result.stdout, b"")
        self.assertIn(os.fsencode(str(missing)), result.stderr)

    def test_directory_fails_with_exit_code_1(self):
        directory = self.tmp / "a directory"
        directory.mkdir()
        result = self.run_key_id(str(directory))
        self.assertEqual(result.returncode, 1)
        self.assertEqual(result.stdout, b"")
        self.assertIn(os.fsencode(str(directory)), result.stderr)

    @unittest.skipIf(
        hasattr(os, "geteuid") and os.geteuid() == 0,
        "root bypasses file permission bits",
    )
    def test_unreadable_file_fails_with_exit_code_1(self):
        path = self.write_file("secret.pub", self.rsa_pem)
        path.chmod(0o000)
        self.addCleanup(lambda: path.chmod(0o644))
        result = self.run_key_id(str(path))
        self.assertEqual(result.returncode, 1)
        self.assertEqual(result.stdout, b"")
        self.assertIn(os.fsencode(str(path)), result.stderr)

    # -- read failure after a successful open (exit code 1) -------------

    def _preload_env(self, **extra):
        env = dict(os.environ)
        preload = READFAIL_PRELOAD
        if env.get("LD_PRELOAD"):
            preload = preload + ":" + env["LD_PRELOAD"]
        env["LD_PRELOAD"] = preload
        env.update(extra)
        return env

    @requires_readfail_preload
    def test_read_error_after_partial_content_fails_with_exit_code_1(self):
        path = self.write_file(
            "readfail/key.pub", wrap_public_pem(self.rsa_der, 64, b"\n")
        )

        # Control: unarmed preload still succeeds.
        healthy = subprocess.run(
            [SEALMARK_BIN, "key-id", str(path)],
            capture_output=True,
            env=self._preload_env(SEALMARK_READFAIL_PATH=str(path)),
        )
        self.assertEqual(healthy.returncode, 0, healthy.stderr)

        size = path.stat().st_size
        for after in (1, 100, size // 2, size - 1):
            with self.subTest(after=after):
                result = subprocess.run(
                    [SEALMARK_BIN, "key-id", str(path)],
                    capture_output=True,
                    env=self._preload_env(
                        SEALMARK_READFAIL_PATH=str(path),
                        SEALMARK_READFAIL_AFTER=str(after),
                    ),
                )
                self.assertEqual(result.returncode, 1, result.stderr)
                self.assertEqual(result.stdout, b"")
                self.assertIn(b"read", result.stderr.lower())
                self.assertIn(os.fsencode(str(path)), result.stderr)
                self.assertNotIn(b"spki-sha256", result.stderr)

    # -- usage errors (exit code 2) --------------------------------------

    def assertUsageError(self, result):
        self.assertEqual(result.returncode, 2)
        self.assertEqual(result.stdout, b"")
        self.assertIn(b"Usage", result.stderr)
        self.assertIn(b"key-id", result.stderr)
        self.assertTrue(result.stderr.endswith(b"\n"))

    def test_missing_path_argument_is_usage_error(self):
        self.assertUsageError(self.run_sealmark("key-id"))

    def test_empty_path_argument_is_usage_error(self):
        self.assertUsageError(self.run_sealmark("key-id", ""))

    def test_extra_argument_is_usage_error(self):
        path = self.write_file("ed.pub", self.ed_pem)
        self.assertUsageError(
            self.run_sealmark("key-id", str(path), "extra")
        )

    def test_no_arguments_is_usage_error(self):
        result = self.run_sealmark()
        self.assertEqual(result.returncode, 2)
        self.assertEqual(result.stdout, b"")

    # -- pre-existing features kept compatible ---------------------------

    def test_version_output_unchanged(self):
        result = self.run_sealmark("--version")
        self.assertEqual(result.returncode, 0)
        self.assertEqual(result.stderr, b"")
        self.assertEqual(result.stdout, b"sealmark 0.1.0\n")

    def test_digest_still_hashes_raw_bytes_not_parsed_key(self):
        # digest's result must remain the raw-byte digest, which differs from
        # the key fingerprint and changes when the PEM is re-wrapped.
        path = self.write_file("ed.pub", self.ed_pem)
        rewrapped = self.write_file(
            "ed-rewrapped.pub", wrap_public_pem(self.ed_der, 10, b"\r\n")
        )
        d1 = self.run_sealmark("digest", str(path))
        d2 = self.run_sealmark("digest", str(rewrapped))
        k1 = self.run_key_id(str(path))
        self.assertEqual(d1.returncode, 0, d1.stderr)
        self.assertEqual(d2.returncode, 0, d2.stderr)
        self.assertNotEqual(d1.stdout, d2.stdout)  # layout changes raw digest
        self.assertEqual(
            d1.stdout,
            b"sha256:" + hashlib.sha256(self.ed_pem).hexdigest().encode()
            + b"\n",
        )
        self.assertNotEqual(k1.stdout, d1.stdout)


if __name__ == "__main__":
    unittest.main(verbosity=2)
